# Generated by Django 3.1 on 2020-09-03 14:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200903_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 3, 14, 43, 47, 42410, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='joined_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 3, 14, 43, 47, 42410, tzinfo=utc)),
        ),
    ]
