# Generated by Django 3.1 on 2020-09-07 15:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20200903_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 7, 15, 16, 0, 740713, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='joined_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 7, 15, 16, 0, 740713, tzinfo=utc)),
        ),
    ]
