# Generated by Django 3.1 on 2020-09-07 16:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20200907_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 7, 16, 30, 9, 166532, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='joined_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 7, 16, 30, 9, 165535, tzinfo=utc)),
        ),
    ]
