# Generated by Django 3.1 on 2020-09-07 15:16

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True, null=True)),
                ('note_image', models.ImageField(blank=True, null=True, upload_to='notes/%Y/%m/')),
                ('note_file', models.FileField(upload_to='notes/%Y/%m/')),
                ('created_on', models.DateTimeField(default=datetime.datetime(2020, 9, 7, 15, 16, 0, 741708, tzinfo=utc))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
