# Generated by Django 3.1 on 2020-09-07 16:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='branch',
            field=models.CharField(choices=[('CS', 'Computer Science'), ('MECH', 'Mechanical Engineering'), ('EEE', 'Electrical'), ('IT', 'Information Technology'), ('COM', 'Communication Technology'), ('PROG', 'Programming'), ('OT', 'Other')], default='OT', max_length=4),
        ),
        migrations.AlterField(
            model_name='note',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 7, 16, 30, 9, 184440, tzinfo=utc)),
        ),
    ]
